include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    require_trailing_commas: warning
    unawaited_futures: warning

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_shrink_expand
    - require_trailing_commas
    - directives_ordering
    - prefer_final_locals
    - unnecessary_lambdas
    - prefer_iterable_whereType
    - unawaited_futures
    - use_build_context_synchronously
    - avoid_print
