import 'dart:io';

import 'package:statistics/statistics.dart';

void main() {
  for (final (profile, seed) in [
    ('normal', _normalSeed),
    ('pcos', _pcosSeed),
  ]) {
    stdout.write('Building $profile... ');
    final monitor = _buildMonitor(seed);
    final path = 'assets/population/network_$profile.json';
    File(path).writeAsStringSync(monitor.toJsonEncoded(pretty: true));
    stdout.write('saved ($path)\n');
  }
}

BayesEventMonitor _buildMonitor(List<List<String>> seed) {
  final monitor = BayesEventMonitor('cycleMonitor');
  for (final event in seed) {
    final Map<String, String> vals = {};
    for (final e in event) {
      final int i = e.indexOf('=');
      vals[e.substring(0, i)] = e.substring(i + 1);
    }

    final String phase = vals['PHASE']!;
    final String flow = vals['FLOW']!;

    monitor.notifyEvent(['PHASE=$phase']);

    monitor.notifyEvent(['FLOW=$flow', 'PHASE=$phase']);

    if (vals.containsKey('DISCHARGE')) {
      monitor.notifyEvent(['DISCHARGE=${vals['DISCHARGE']}', 'PHASE=$phase']);
    }

    for (final symptom in _allSymptoms) {
      final String val = vals[symptom] ?? 'FALSE';
      monitor.notifyEvent(['$symptom=$val', 'PHASE=$phase']);
    }

    for (final mood in _allMoods) {
      final String val = vals[mood] ?? 'FALSE';
      monitor.notifyEvent(['$mood=$val', 'PHASE=$phase']);
    }

    for (final key in ['STRESS', 'SLEEP', 'SEX']) {
      if (vals.containsKey(key)) {
        monitor.notifyEvent(['$key=${vals[key]}', 'PHASE=$phase']);
      }
    }
  }
  return monitor;
}

const List<String> _allSymptoms = [
  'SYMPTOM_PERIODCRAMPS', 'SYMPTOM_OVULATIONPAIN', 'SYMPTOM_TENDERBREASTS',
  'SYMPTOM_HEADACHE', 'SYMPTOM_FATIGUE', 'SYMPTOM_BLOATING', 'SYMPTOM_ACNE',
];

const List<String> _allMoods = [
  'MOOD_HAPPY', 'MOOD_HIGHLIBIDO', 'MOOD_IRRITABLE',
  'MOOD_ANXIOUS', 'MOOD_DEPRESSED', 'MOOD_EXHAUSTED',
];

const List<List<String>> _normalSeed = [
  // Cycle: 1
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','MOOD_DEPRESSED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE'],

  // Cycle: 2
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_DEPRESSED=TRUE','MOOD_ANXIOUS=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','MOOD_EXHAUSTED=TRUE'],

  // Cycle: 3
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','SYMPTOM_HEADACHE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_DEPRESSED=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],

  // Cycle: 4
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=LIGHT','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=LIGHT','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','MOOD_DEPRESSED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_DEPRESSED=TRUE','MOOD_IRRITABLE=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE'],

  // Cycle: 5
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE','SLEEP=EXCELLENT'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','MOOD_DEPRESSED=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_EXHAUSTED=TRUE','MOOD_ANXIOUS=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],

  // Extra 10 Days
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
];

const List<List<String>> _pcosSeed = [
  // Cycle: 1
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_ACNE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=LIGHT','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','MOOD_DEPRESSED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],

  // Cycle: 2
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=LIGHT','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','SLEEP=POOR'],

  // Cycle: 3
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_ACNE=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=LIGHT','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_DEPRESSED=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],

  // Cycle: 4
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','MOOD_EXHAUSTED=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_FATIGUE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=LIGHT','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HAPPY=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=WATERY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=OVULATORY','FLOW=NONE','DISCHARGE=EGGWHITE','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_OVULATIONPAIN=TRUE','MOOD_HIGHLIBIDO=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=OVULATORY','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_HAPPY=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=MEDIUM'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=CREAMY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_TENDERBREASTS=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE','STRESS=HIGH'],
  ['PHASE=LUTEAL','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','SYMPTOM_BLOATING=TRUE','MOOD_DEPRESSED=TRUE','MOOD_IRRITABLE=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=LUTEAL','FLOW=LIGHT','DISCHARGE=STICKY','PREV_PHASE=LUTEAL','PREV_FLOW=NONE','SYMPTOM_BLOATING=TRUE','SYMPTOM_TENDERBREASTS=TRUE','MOOD_EXHAUSTED=TRUE','SLEEP=POOR'],

  // Extra 10 Days
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=LUTEAL','PREV_FLOW=LIGHT','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_BLOATING=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH','SLEEP=POOR'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_EXHAUSTED=TRUE','STRESS=HIGH'],
  ['PHASE=MENSTRUAL','FLOW=HEAVY','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_HEADACHE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=STICKY','PREV_PHASE=MENSTRUAL','PREV_FLOW=HEAVY','SYMPTOM_PERIODCRAMPS=TRUE','SYMPTOM_ACNE=TRUE','MOOD_IRRITABLE=TRUE','STRESS=MEDIUM'],
  ['PHASE=MENSTRUAL','FLOW=MEDIUM','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE'],
  ['PHASE=MENSTRUAL','FLOW=LIGHT','DISCHARGE=CREAMY','PREV_PHASE=MENSTRUAL','PREV_FLOW=MEDIUM','SYMPTOM_ACNE=TRUE','MOOD_DEPRESSED=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=MENSTRUAL','PREV_FLOW=LIGHT','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=DRY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_FATIGUE=TRUE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
  ['PHASE=FOLLICULAR','FLOW=NONE','DISCHARGE=STICKY','PREV_PHASE=FOLLICULAR','PREV_FLOW=NONE','SYMPTOM_ACNE=TRUE','MOOD_ANXIOUS=TRUE'],
];
