// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:buritto/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DischargeAdapter());
    registerAdapter(FlowAdapter());
    registerAdapter(LogAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MoodAdapter());
    registerAdapter(PhaseAdapter());
    registerAdapter(QuantumLogAdapter());
    registerAdapter(SexAdapter());
    registerAdapter(SleepAdapter());
    registerAdapter(StressAdapter());
    registerAdapter(SymptomAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DischargeAdapter());
    registerAdapter(FlowAdapter());
    registerAdapter(LogAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(MoodAdapter());
    registerAdapter(PhaseAdapter());
    registerAdapter(QuantumLogAdapter());
    registerAdapter(SexAdapter());
    registerAdapter(SleepAdapter());
    registerAdapter(StressAdapter());
    registerAdapter(SymptomAdapter());
  }
}
